name: Test STO Action

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    environment: HARNESS
    steps:
      - name: Checkout DVPWA Code
        uses: actions/checkout@v4
        with:
          repository: anxolerd/dvpwa
          path: code  # ← Use a clearer name

      - name: Run Security Scan
        uses: williamwissemann/sto-plugin-action@main
        with:
          docker-image-tag: dev 
          harness-token: ${{ secrets.HARNESS_PAT_TOKEN }}
          harness-org-id: 'STO'
          harness-project-id: 'STO_LAB'
          scanner: 'bandit'
          workspace: 'code'  # ← Match the path above
