name: Test STO Action

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: anxolerd/dvpwa  # Test vulnerable app

      - uses: williamwissemann/sto-plugin-action@main
        with:
          harness-token: ${{ secrets.HARNESS_PAT_TOKEN }}
          harness-org-id: 'default'
          harness-project-id: 'test'
          scanner_name: 'bandit'
